// src/components/Slider.vue
<template>
  <div>
    <div class="text-center">
      <label>{{ label }}</label>
    </div>
    <div class="flex justify-center">
      <input
        :value="modelValue"
        type="range"
        min="0"
        :max="max"
        @input="updateValue"
      />
    </div>
  </div>
</template>

<script>
export default {
  name: "Slider",
  props: {
    label: {
      type: String,
      required: true,
    },
    modelValue: {
      type: Number,
      required: true,
    },
    max: {
      type: Number,
      required: false,
      default: 100,
    }
  },
  methods: {
    updateValue(event) {
      this.$emit("update:model-value", Number(event.target.value) || 0);
    },
  },
};
</script>

<style scoped></style>

// src/sidebar/Slider.svelte
<script>
	import config from '../config.js'

	export let label
	export let disabled = false
	export let value

	const { min, max } = config.slider
</script>

<div class={$$props.class}>
	<div class="range-value text-center">
		<label for="range" style={disabled ? 'color: gray' : ''}>{label}</label>
	</div>
	<div class="flex justify-center mt-1">
		<input id="range" type="range" {disabled} bind:value {min} {max} />
	</div>
</div>
