// src/lib/components/slider/Slider.svelte
<script>
	import './slider.css'
	import config from '../../../config.js'

	export let label
	export let disabled = false
	export let value

	const { min, max } = config.slider
</script>

<div class={$$props.class}>
	<div class="range-value text-center">
		<label for="range" style={disabled ? 'color: gray' : ''}>{label}</label>
	</div>
	<div class="flex justify-center mt-1">
		<input id="range" type="range" {disabled} bind:value {min} {max} />
	</div>
</div>

// src/components/sort-visualizer/components/sidebar/components/Slider.vue
@@ -1,41 +0,0 @@
<template>
	<div>
		<div class='text-center'>
			<label>{{ label }}</label>
		</div>
		<div class='flex justify-center'>
			<input :value='value' type='range' :min='min' :max='max' @input.stop='updateValue' />
		</div>
	</div>
</template>

<script>
export default {
	name: 'Slider',
	props: {
		label: {
			type: String,
			required: true
		},
		value: {
			type: Number,
			required: true
		},
		max: {
			type: Number,
			required: false,
			default: 100
		},
		min: {
			type: Number,
			required: false,
			default: 5
		}
	},
	methods: {
		updateValue(event) {
			this.$emit('input', Number(event.target.value) || 0);
		}
	}
};
</script>
